"use strict";
const { OAuth2Client } = require("google-auth-library");
const axios = require("axios");
const crypto = require("node:crypto");
const logger = require("../utils/logger");
const { encrypt, decrypt } = require("../utils/cryptoUtils");
const OAuthState = require("../models/OAuthState");
const GoogleConnection = require("../models/GoogleBusinessConnection");
const TenantSocialCredential = require("../models/TenantSocialCredential");
const READ_ONLY = true;
const SCOPE = "https://www.googleapis.com/auth/business.manage";
async function oauth(tenantId) { const row = await TenantSocialCredential.findOne({ tenantId, platform: "google_business", enabled: true }).select("+clientId +clientSecret"); if (!row) throw new Error("Google Business Profile is not configured for this tenant"); const redirect = row.redirectUri; if (process.env.NODE_ENV === "production" && !/^https:\/\//i.test(redirect)) throw new Error("Google redirect URI must use HTTPS in production"); return { client: new OAuth2Client(decrypt(row.clientId), decrypt(row.clientSecret), redirect), redirect }; }
async function createAuthorizationRequest(user, returnTo) { const tenantId = user?.tenantId || user?._id; if (!tenantId || !user?._id) throw new Error("Tenant context is required"); const { client, redirect } = await oauth(tenantId); const state = crypto.randomBytes(32).toString("hex"); await OAuthState.create({ userId: user._id, tenantId, platform: "google_business", stateHash: crypto.createHash("sha256").update(state).digest("hex"), redirectUri: redirect, returnTo: returnTo || process.env.FRONTEND_URL || "/", expiresAt: new Date(Date.now() + 10 * 60 * 1000) }); return client.generateAuthUrl({ access_type: "offline", prompt: "consent", scope: [SCOPE], state }); }
async function consume(state) { const hash = crypto.createHash("sha256").update(String(state || "")).digest("hex"); const tx = await OAuthState.findOneAndDelete({ platform: "google_business", stateHash: hash, expiresAt: { $gt: new Date() } }); if (!tx) throw new Error("Invalid or expired OAuth state"); return tx; }
async function exchangeCodeForTokens(code, tenantId) { if (!code) throw new Error("Authorization code is required"); const { client } = await oauth(tenantId); const { tokens } = await client.getToken(code); if (!tokens.access_token || !tokens.refresh_token) throw new Error("Google did not return the required tokens; reconnect with offline access"); return { accessToken: encrypt(tokens.access_token), refreshToken: encrypt(tokens.refresh_token), tokenExpiry: new Date(tokens.expiry_date || Date.now() + Number(tokens.expires_in || 3600) * 1000) }; }
async function connectFromCallback(code, state) { const tx = await consume(state); const token = await exchangeCodeForTokens(code, tx.tenantId); const saved = await GoogleConnection.findOneAndUpdate({ tenantId: tx.tenantId, userId: tx.userId }, { tenantId: tx.tenantId, userId: tx.userId, ...token, status: "connected", connectedAt: new Date() }, { upsert: true, new: true, setDefaultsOnInsert: true }); return { userId: tx.userId, tenantId: tx.tenantId, connection: saved, returnTo: tx.returnTo }; }
async function connection(user) { if (!user?._id) throw new Error("User authentication required"); if (GoogleConnection.db.readyState !== 1) throw new Error("Database connection is required for Google Business Profile integration"); return GoogleConnection.findOne({ tenantId: user.tenantId || user._id, userId: user._id }).select("+accessToken +refreshToken"); }
async function getValidAccessToken(user) { const c = await connection(user); if (!c || c.status === "revoked") throw new Error("Google Business Profile is not connected; reconnect is required"); if (c.accessToken && c.tokenExpiry && new Date(c.tokenExpiry).getTime() - Date.now() > 300000) return decrypt(c.accessToken); try { const refresh = decrypt(c.refreshToken); const { client } = await oauth(user.tenantId || user._id); client.setCredentials({ refresh_token: refresh }); const { credentials } = await client.refreshAccessToken(); c.accessToken = encrypt(credentials.access_token); c.tokenExpiry = new Date(credentials.expiry_date || Date.now() + Number(credentials.expires_in || 3600) * 1000); if (credentials.refresh_token) c.refreshToken = encrypt(credentials.refresh_token); c.status = "connected"; await c.save(); return credentials.access_token; } catch (error) { c.status = "revoked"; await c.save(); logger.error("google.token.refresh.failed", { userId: user._id, tenantId: user.tenantId, error: error.message }); throw new Error("Google token refresh failed; reconnect is required"); } }
function normalizeLocation(location = {}) { const a = location.storefrontAddress || {}; const lines = Array.isArray(a.addressLines) ? a.addressLines.join(", ") : ""; return { businessId: location.name || "", businessName: location.title || "", category: location.categories?.primaryCategory?.displayName || "", address: { streetName: lines, city: a.locality || "", state: a.administrativeArea || "", pincode: a.postalCode || "", country: a.regionCode || "", formattedAddress: [lines, a.locality, a.administrativeArea, a.postalCode, a.regionCode].filter(Boolean).join(", ") }, phoneNumber: location.phoneNumbers?.primaryPhone || "", website: location.websiteUri || "", description: location.profile?.description || "", businessHours: { periods: location.regularHours?.periods || [] }, locationDetails: { latitude: location.latlng?.latitude || 0, longitude: location.latlng?.longitude || 0 } }; }
const READ_MASK = "name,title,categories,storefrontAddress,phoneNumbers,websiteUri,profile,regularHours,latlng";
async function fetchAllProfilesForUser(user) { const token = await getValidAccessToken(user); const headers = { Authorization: `Bearer ${token}` }; const accounts = (await axios.get("https://mybusinessaccountmanagement.googleapis.com/v1/accounts", { headers })).data.accounts || []; const profiles = []; for (const account of accounts) { const data = (await axios.get(`https://mybusinessbusinessinformation.googleapis.com/v1/${account.name}/locations`, { headers, params: { readMask: READ_MASK } })).data; profiles.push(...(data.locations || []).map(normalizeLocation)); } return profiles; }
async function fetchProfileByLocationName(user, name) { if (!/^locations\/[A-Za-z0-9_-]+$/.test(name || "")) throw new Error("Invalid location ID"); const token = await getValidAccessToken(user); const data = (await axios.get(`https://mybusinessbusinessinformation.googleapis.com/v1/${name}`, { headers: { Authorization: `Bearer ${token}` }, params: { readMask: READ_MASK } })).data; return normalizeLocation(data); }
function assertReadOnly(operation) { if (operation && /patch|put|post|delete|update|create/i.test(operation)) throw new Error(`Read-only violation: ${operation}`); return true; }
module.exports = { READ_ONLY, assertReadOnly, createAuthorizationRequest, connectFromCallback, exchangeCodeForTokens, getValidAccessToken, normalizeLocation, fetchAllProfilesForUser, fetchProfileByLocationName, connection };
