name: CICD

on:
  push:
    branches: [soumen]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t soumendigitalmitro/business_list:latest .

      - name: Publish image to Docker Hub
        run: docker push soumendigitalmitro/business_list:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Change this to ubuntu-latest or a self-hosted runner
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            docker pull soumendigitalmitro/business_list:latest
            
            # Stop and remove the old container if it exists
            docker rm -f nodejs-app-container || true
            
            # Run the new container
            docker run -d -p 5000:5000 --name nodejs-app-container soumendigitalmitro/business_list:latest